stages:
  - prepare
  - gateware
  - software

default:
  tags:
    - xilinx

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado_and_Vitis/2020.2.2/Vivado/2020.2
  XILINX_VITIS: /non-free/Xilinx/Vivado_and_Vitis/2020.2.2/Vitis/2020.2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

# Gateware jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description, as to simplify job descriptions
gw_cctrl_bmb7:
  before_script:
    - cd gateware/syn/cctrl_bmb7 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH time make cctrl_bmb7_top.bit && PATH=$XILINX_VIVADO/bin:$PATH time make cctrl_bmb7_top.mmi
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - gateware/syn/cctrl_bmb7/cctrl_bmb7_top.bit
      - gateware/syn/cctrl_bmb7/cctrl_bmb7_top.mmi
      - gateware/syn/cctrl_bmb7/_xilinx/cctrl_bmb7_top/*.runs/impl_1/*.rpt
      - gateware/syn/cctrl_bmb7/system.xsa

gw_cctrl_marble:
  before_script:
    - cd gateware/syn/cctrl_marble && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH time make cctrl_marble_top.bit && PATH=$XILINX_VIVADO/bin:$PATH time make cctrl_marble_top.mmi
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - gateware/syn/cctrl_marble/cctrl_marble_top.bit
      - gateware/syn/cctrl_marble/cctrl_marble_top.mmi
      - gateware/syn/cctrl_marble/_xilinx/cctrl_marble_top/*.runs/impl_1/*.rpt
      - gateware/syn/cctrl_marble/system_marble.xsa

# Software jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description...
sw_cctrl_bmb7:
  before_script:
    - cd software/app/cctrl
  stage: software
  script:
    - make TARGET=cctrl_bmb7 clean && PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/microblaze/lin/bin:$PATH time make TARGET=cctrl_bmb7 all bundle
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_cctrl_bmb7
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - software/app/cctrl/cctrl_bmb7.elf
      - software/app/cctrl/cctrl_bmb7.elf.size
      - software/app/cctrl/download_bmb7.bit

sw_cctrl_marble:
  before_script:
    - cd software/app/cctrl
  stage: software
  script:
    - make TARGET=cctrl_marble clean && PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/microblaze/lin/bin:$PATH time make TARGET=cctrl_marble all bundle
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_cctrl_marble
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - software/app/cctrl/cctrl_marble.elf
      - software/app/cctrl/cctrl_marble.elf.size
      - software/app/cctrl/download_marble.bit
