stages:
  - prepare
  - gateware
  - software

default:
  tags:
    - xilinx

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado_and_Vitis/2020.2.2/Vivado/2020.2
  XILINX_VITIS: /non-free/Xilinx/Vivado_and_Vitis/2020.2.2/Vitis/2020.2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

# Gateware jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description, as to simplify job descriptions
gw_cctrl_aurora_8b10b_marble:
  before_script:
    - cd gateware/syn/cctrl_aurora_8b10b_marble && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH make cctrl_aurora_8b10b_marble_top.bit && PATH=$XILINX_VIVADO/bin:$PATH make cctrl_aurora_8b10b_marble_top.mmi
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - gateware/syn/cctrl_aurora_8b10b_marble/cctrl_aurora_8b10b_marble_top.bit
      - gateware/syn/cctrl_aurora_8b10b_marble/cctrl_aurora_8b10b_marble_top.mmi
      - gateware/syn/cctrl_aurora_8b10b_marble/_xilinx/cctrl_aurora_8b10b_marble_top/*.runs/impl_1/*.rpt
      - gateware/syn/cctrl_aurora_8b10b_marble/system.xsa

gw_cctrl_aurora_64b66b_marble:
  before_script:
    - cd gateware/syn/cctrl_aurora_64b66b_marble && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH make cctrl_aurora_64b66b_marble_top.bit && PATH=$XILINX_VIVADO/bin:$PATH make cctrl_aurora_64b66b_marble_top.mmi
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - gateware/syn/cctrl_aurora_64b66b_marble/cctrl_aurora_64b66b_marble_top.bit
      - gateware/syn/cctrl_aurora_64b66b_marble/cctrl_aurora_64b66b_marble_top.mmi
      - gateware/syn/cctrl_aurora_64b66b_marble/_xilinx/cctrl_aurora_64b66b_marble_top/*.runs/impl_1/*.rpt
      - gateware/syn/cctrl_aurora_64b66b_marble/system.xsa

# Software jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description...
sw_cctrl_aurora_8b10b_marble:
  before_script:
    - cd software/app/cctrl_aurora_8b10b
  stage: software
  script:
    - make TARGET=cctrl_aurora_8b10b_marble clean && PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/microblaze/lin/bin:$PATH make APP=cctrl_aurora_8b10b PLATFORM=marble all
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_cctrl_aurora_8b10b_marble
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - software/app/cctrl_aurora_8b10b/cctrl_aurora_8b10b_marble.elf
      - software/app/cctrl_aurora_8b10b/cctrl_aurora_8b10b_marble.elf.size
      - software/app/cctrl_aurora_8b10b/cctrl_aurora_8b10b_marble*.bit

sw_cctrl_aurora_64b66b_marble:
  before_script:
    - cd software/app/cctrl_aurora_64b66b
  stage: software
  script:
    - make TARGET=cctrl_aurora_64b66b_marble clean && PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/microblaze/lin/bin:$PATH make APP=cctrl_aurora_64b66b PLATFORM=marble all
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_cctrl_aurora_64b66b_marble
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - software/app/cctrl_aurora_64b66b/cctrl_aurora_64b66b_marble.elf
      - software/app/cctrl_aurora_64b66b/cctrl_aurora_64b66b_marble.elf.size
      - software/app/cctrl_aurora_64b66b/cctrl_aurora_64b66b_marble*.bit
