/*
 * S25FLxxxS flash memory definitions
 */

#ifndef _S25FLxxxS_H_
#define _S25FLxxxS_H_

#include "util.h"

/*
 * Flash memory definitions
 */
#define S25FLXXXS_SR1_REG     0x05

#define S25FLXXXS_SR1_BP_SIZE    3
#define S25FLXXXS_SR1_BP_SHIFT   2
#define S25FLXXXS_SR1_BP_MASK    REG_GEN_MASK(S25FLXXXS_SR1_BP_SHIFT, S25FLXXXS_SR1_BP_SIZE)
#define S25FLXXXS_SR1_BP_R(reg)  REG_GEN_READ(reg, S25FLXXXS_SR1_BP_SHIFT, S25FLXXXS_SR1_BP_SIZE)

#define S25FLXXXS_CR1_REG     0x35

#define S25FLXXXS_CR1_TBPROT_SIZE    1
#define S25FLXXXS_CR1_TBPROT_SHIFT   5
#define S25FLXXXS_CR1_TBPROT_MASK    REG_GEN_MASK(S25FLXXXS_CR1_TBPROT_SHIFT, S25FLXXXS_CR1_TBPROT_SIZE)
#define S25FLXXXS_CR1_TBPROT_R(reg)  REG_GEN_READ(reg, S25FLXXXS_CR1_TBPROT_SHIFT, S25FLXXXS_CR1_TBPROT_SIZE)

#endif /* _S25FLXXXS_H_ */
