# ----------------------------------------------------------------------
# ----------- Marble .XDC pinout auto-generated by xdcgen.py -----------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# ------------------------------ pmod J17 ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN F13 [get_ports {bus_digitizer_J17[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J17[0]}]
set_property PACKAGE_PIN E12 [get_ports {bus_digitizer_J17[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J17[1]}]
set_property PACKAGE_PIN G9 [get_ports {bus_digitizer_J17[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J17[2]}]
set_property PACKAGE_PIN G10 [get_ports {bus_digitizer_J17[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J17[3]}]
set_property PACKAGE_PIN F14 [get_ports {bus_digitizer_J17[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J17[4]}]
set_property PACKAGE_PIN E13 [get_ports {bus_digitizer_J17[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J17[5]}]
set_property PACKAGE_PIN F9 [get_ports {bus_digitizer_J17[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J17[6]}]
set_property PACKAGE_PIN F8 [get_ports {bus_digitizer_J17[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J17[7]}]
# ----------------------------------------------------------------------
# ------------------------------ pmod J18 ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN K22 [get_ports {bus_digitizer_J18[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J18[0]}]
set_property PACKAGE_PIN F24 [get_ports {bus_digitizer_J18[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J18[1]}]
set_property PACKAGE_PIN G24 [get_ports {bus_digitizer_J18[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J18[2]}]
set_property PACKAGE_PIN L22 [get_ports {bus_digitizer_J18[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J18[3]}]
set_property PACKAGE_PIN D24 [get_ports {bus_digitizer_J18[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J18[4]}]
set_property PACKAGE_PIN H23 [get_ports {bus_digitizer_J18[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J18[5]}]
set_property PACKAGE_PIN H24 [get_ports {bus_digitizer_J18[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J18[6]}]
set_property PACKAGE_PIN D23 [get_ports {bus_digitizer_J18[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J18[7]}]
# ----------------------------------------------------------------------
# ------------------------------ hdmi J19 ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN A13 [get_ports {bus_digitizer_J19[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J19[0]}]
set_property PACKAGE_PIN H13 [get_ports {bus_digitizer_J19[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J19[1]}]
set_property PACKAGE_PIN B12 [get_ports {bus_digitizer_J19[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_J19[2]}]
set_property PACKAGE_PIN J13 [get_ports {bus_digitizer_J19[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J19[3]}]
set_property PACKAGE_PIN B10 [get_ports {bus_digitizer_J19[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J19[4]}]
set_property PACKAGE_PIN C14 [get_ports {bus_digitizer_J19[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J19[5]}]
set_property PACKAGE_PIN A12 [get_ports {bus_digitizer_J19[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J19[6]}]
set_property PACKAGE_PIN A9 [get_ports {bus_digitizer_J19[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J19[7]}]
set_property PACKAGE_PIN B11 [get_ports {bus_digitizer_J19[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_J19[8]}]
set_property PACKAGE_PIN A8 [get_ports {bus_digitizer_J19[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J19[9]}]
set_property PACKAGE_PIN A10 [get_ports {bus_digitizer_J19[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J19[10]}]
set_property PACKAGE_PIN C13 [get_ports {bus_digitizer_J19[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_J19[11]}]
# ----------------------------------------------------------------------
# ---------------------------- LMK01801 U1 -----------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN G16 [get_ports {bus_digitizer_U1[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U1[0]}]
set_property PACKAGE_PIN H16 [get_ports {bus_digitizer_U1[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U1[4]}]
set_property PACKAGE_PIN J21 [get_ports {bus_digitizer_U1[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U1[5]}]
# ----------------------------------------------------------------------
# ----------------------------- AD9653 U2 ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN D19 [get_ports {bus_digitizer_U2[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[4]}]
set_property PACKAGE_PIN L20 [get_ports {bus_digitizer_U2[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[5]}]
set_property PACKAGE_PIN G20 [get_ports {bus_digitizer_U2[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[6]}]
set_property PACKAGE_PIN D20 [get_ports {bus_digitizer_U2[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[8]}]
set_property PACKAGE_PIN H17 [get_ports {bus_digitizer_U2[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[9]}]
set_property PACKAGE_PIN H19 [get_ports {bus_digitizer_U2[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[10]}]
set_property PACKAGE_PIN G17 [get_ports {bus_digitizer_U2[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[11]}]
set_property PACKAGE_PIN F18 [get_ports {bus_digitizer_U2[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[12]}]
set_property PACKAGE_PIN F19 [get_ports {bus_digitizer_U2[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[13]}]
set_property PACKAGE_PIN G19 [get_ports {bus_digitizer_U2[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[14]}]
set_property PACKAGE_PIN H18 [get_ports {bus_digitizer_U2[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[15]}]
set_property PACKAGE_PIN J18 [get_ports {bus_digitizer_U2[16]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[16]}]
set_property PACKAGE_PIN F20 [get_ports {bus_digitizer_U2[17]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[17]}]
set_property PACKAGE_PIN E20 [get_ports {bus_digitizer_U2[18]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[18]}]
set_property PACKAGE_PIN L18 [get_ports {bus_digitizer_U2[19]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[19]}]
set_property PACKAGE_PIN J19 [get_ports {bus_digitizer_U2[20]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[20]}]
set_property PACKAGE_PIN E21 [get_ports {bus_digitizer_U2[22]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U2[22]}]
set_property PACKAGE_PIN K20 [get_ports {bus_digitizer_U2[23]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[23]}]
set_property PACKAGE_PIN J20 [get_ports {bus_digitizer_U2[24]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[24]}]
set_property PACKAGE_PIN M17 [get_ports {bus_digitizer_U2[25]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[25]}]
set_property PACKAGE_PIN L19 [get_ports {bus_digitizer_U2[26]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U2[26]}]
# ----------------------------------------------------------------------
# ----------------------------- AD9653 U3 ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN K16 [get_ports {bus_digitizer_U3[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[3]}]
set_property PACKAGE_PIN E10 [get_ports {bus_digitizer_U3[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[4]}]
set_property PACKAGE_PIN B15 [get_ports {bus_digitizer_U3[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[5]}]
set_property PACKAGE_PIN D14 [get_ports {bus_digitizer_U3[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[6]}]
set_property PACKAGE_PIN E15 [get_ports {bus_digitizer_U3[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[7]}]
set_property PACKAGE_PIN A15 [get_ports {bus_digitizer_U3[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[8]}]
set_property PACKAGE_PIN E16 [get_ports {bus_digitizer_U3[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[9]}]
set_property PACKAGE_PIN W25 [get_ports {bus_digitizer_U3[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U3[10]}]
set_property PACKAGE_PIN E22 [get_ports {bus_digitizer_U3[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U3[11]}]
set_property PACKAGE_PIN J15 [get_ports {bus_digitizer_U3[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[12]}]
set_property PACKAGE_PIN C12 [get_ports {bus_digitizer_U3[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[13]}]
set_property PACKAGE_PIN K18 [get_ports {bus_digitizer_U3[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[14]}]
set_property PACKAGE_PIN H14 [get_ports {bus_digitizer_U3[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[15]}]
set_property PACKAGE_PIN B14 [get_ports {bus_digitizer_U3[16]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[16]}]
set_property PACKAGE_PIN A14 [get_ports {bus_digitizer_U3[18]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[18]}]
set_property PACKAGE_PIN J16 [get_ports {bus_digitizer_U3[19]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[19]}]
set_property PACKAGE_PIN G14 [get_ports {bus_digitizer_U3[20]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[20]}]
set_property PACKAGE_PIN C21 [get_ports {bus_digitizer_U3[21]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U3[21]}]
set_property PACKAGE_PIN K17 [get_ports {bus_digitizer_U3[22]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[22]}]
set_property PACKAGE_PIN D13 [get_ports {bus_digitizer_U3[23]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[23]}]
set_property PACKAGE_PIN D10 [get_ports {bus_digitizer_U3[24]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[24]}]
set_property PACKAGE_PIN C11 [get_ports {bus_digitizer_U3[25]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[25]}]
set_property PACKAGE_PIN L17 [get_ports {bus_digitizer_U3[26]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U3[26]}]
# ----------------------------------------------------------------------
# ----------------------------- AD9781 U4 ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN J26 [get_ports {bus_digitizer_U4[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U4[0]}]
set_property PACKAGE_PIN G25 [get_ports {bus_digitizer_U4[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U4[1]}]
set_property PACKAGE_PIN D25 [get_ports {bus_digitizer_U4[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U4[2]}]
set_property PACKAGE_PIN AB22 [get_ports {bus_digitizer_U4[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[3]}]
set_property PACKAGE_PIN W24 [get_ports {bus_digitizer_U4[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[4]}]
set_property PACKAGE_PIN AB25 [get_ports {bus_digitizer_U4[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[5]}]
set_property PACKAGE_PIN AA22 [get_ports {bus_digitizer_U4[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[6]}]
set_property PACKAGE_PIN U25 [get_ports {bus_digitizer_U4[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[7]}]
set_property PACKAGE_PIN H22 [get_ports {bus_digitizer_U4[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U4[8]}]
set_property PACKAGE_PIN AD23 [get_ports {bus_digitizer_U4[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[9]}]
set_property PACKAGE_PIN AF23 [get_ports {bus_digitizer_U4[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[10]}]
set_property PACKAGE_PIN V26 [get_ports {bus_digitizer_U4[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[11]}]
set_property PACKAGE_PIN K23 [get_ports {bus_digitizer_U4[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U4[12]}]
set_property PACKAGE_PIN G22 [get_ports {bus_digitizer_U4[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[13]}]
set_property PACKAGE_PIN V23 [get_ports {bus_digitizer_U4[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[14]}]
set_property PACKAGE_PIN AC24 [get_ports {bus_digitizer_U4[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[15]}]
set_property PACKAGE_PIN AA25 [get_ports {bus_digitizer_U4[16]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[16]}]
set_property PACKAGE_PIN AF22 [get_ports {bus_digitizer_U4[17]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[17]}]
set_property PACKAGE_PIN V22 [get_ports {bus_digitizer_U4[18]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[18]}]
set_property PACKAGE_PIN J23 [get_ports {bus_digitizer_U4[19]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U4[19]}]
set_property PACKAGE_PIN U22 [get_ports {bus_digitizer_U4[20]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[20]}]
set_property PACKAGE_PIN AC22 [get_ports {bus_digitizer_U4[21]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[21]}]
set_property PACKAGE_PIN AE26 [get_ports {bus_digitizer_U4[22]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[22]}]
set_property PACKAGE_PIN Y22 [get_ports {bus_digitizer_U4[23]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[23]}]
set_property PACKAGE_PIN W21 [get_ports {bus_digitizer_U4[24]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[24]}]
set_property PACKAGE_PIN U24 [get_ports {bus_digitizer_U4[25]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[25]}]
set_property PACKAGE_PIN H26 [get_ports {bus_digitizer_U4[26]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U4[26]}]
set_property PACKAGE_PIN W23 [get_ports {bus_digitizer_U4[27]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[27]}]
set_property PACKAGE_PIN AD24 [get_ports {bus_digitizer_U4[28]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[28]}]
set_property PACKAGE_PIN AE23 [get_ports {bus_digitizer_U4[29]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[29]}]
set_property PACKAGE_PIN V21 [get_ports {bus_digitizer_U4[30]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[30]}]
set_property PACKAGE_PIN AE22 [get_ports {bus_digitizer_U4[31]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[31]}]
set_property PACKAGE_PIN AC26 [get_ports {bus_digitizer_U4[32]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[32]}]
set_property PACKAGE_PIN U26 [get_ports {bus_digitizer_U4[33]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[33]}]
set_property PACKAGE_PIN V24 [get_ports {bus_digitizer_U4[34]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[34]}]
set_property PACKAGE_PIN AB26 [get_ports {bus_digitizer_U4[35]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[35]}]
set_property PACKAGE_PIN AC23 [get_ports {bus_digitizer_U4[36]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[36]}]
set_property PACKAGE_PIN F23 [get_ports {bus_digitizer_U4[37]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[37]}]
set_property PACKAGE_PIN AD26 [get_ports {bus_digitizer_U4[38]}]
set_property IOSTANDARD LVDS_25 [get_ports {bus_digitizer_U4[38]}]
# ----------------------------------------------------------------------
# ---------------------------- AMC7823 U15 -----------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN J24 [get_ports {bus_digitizer_U15[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U15[1]}]
set_property PACKAGE_PIN J25 [get_ports {bus_digitizer_U15[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U15[2]}]
# ----------------------------------------------------------------------
# ----------------------------- AD7794 U18 -----------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN E25 [get_ports {bus_digitizer_U18[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U18[0]}]
set_property PACKAGE_PIN E26 [get_ports {bus_digitizer_U18[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U18[1]}]
set_property PACKAGE_PIN F25 [get_ports {bus_digitizer_U18[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U18[2]}]
set_property PACKAGE_PIN B21 [get_ports {bus_digitizer_U18[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U18[3]}]
set_property PACKAGE_PIN W26 [get_ports {bus_digitizer_U18[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U18[4]}]
# ----------------------------------------------------------------------
# --------------------------- 74AVC4T245 U27 ---------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN G26 [get_ports {bus_digitizer_U27[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U27[0]}]
# ----------------------------------------------------------------------
# -------------------------- 74AVC4T245 U33U1 --------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN H21 [get_ports {bus_digitizer_U33U1[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U33U1[0]}]
set_property PACKAGE_PIN G21 [get_ports {bus_digitizer_U33U1[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {bus_digitizer_U33U1[1]}]
# ----------------------------------------------------------------------
# ------------------------------ RGMII RX ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN E11 [get_ports {RGMII_RX_CLK}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_RX_CLK}]
set_property PACKAGE_PIN J11 [get_ports {RGMII_RX_CTRL}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_RX_CTRL}]
set_property PACKAGE_PIN J10 [get_ports {RGMII_RXD[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_RXD[0]}]
set_property PACKAGE_PIN J8 [get_ports {RGMII_RXD[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_RXD[1]}]
set_property PACKAGE_PIN H8 [get_ports {RGMII_RXD[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_RXD[2]}]
set_property PACKAGE_PIN H9 [get_ports {RGMII_RXD[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_RXD[3]}]
# ----------------------------------------------------------------------
# ------------------------------ RGMII TX ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN F10 [get_ports {RGMII_TX_CLK}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_TX_CLK}]
set_property PACKAGE_PIN C9 [get_ports {RGMII_TX_CTRL}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_TX_CTRL}]
set_property PACKAGE_PIN H11 [get_ports {RGMII_TXD[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_TXD[0]}]
set_property PACKAGE_PIN H12 [get_ports {RGMII_TXD[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_TXD[1]}]
set_property PACKAGE_PIN D8 [get_ports {RGMII_TXD[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_TXD[2]}]
set_property PACKAGE_PIN D9 [get_ports {RGMII_TXD[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RGMII_TXD[3]}]
# ----------------------------------------------------------------------
# ----------------------------- QSPI Boot ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN C23 [get_ports {BOOT_CS_B}]
set_property IOSTANDARD LVCMOS25 [get_ports {BOOT_CS_B}]
set_property PACKAGE_PIN B24 [get_ports {BOOT_MOSI}]
set_property IOSTANDARD LVCMOS25 [get_ports {BOOT_MOSI}]
set_property PACKAGE_PIN A25 [get_ports {BOOT_MISO}]
set_property IOSTANDARD LVCMOS25 [get_ports {BOOT_MISO}]
set_property PACKAGE_PIN B22 [get_ports {CFG_D02}]
set_property IOSTANDARD LVCMOS25 [get_ports {CFG_D02}]
# ----------------------------------------------------------------------
# ------------------------------ MMC I/O -------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN AE21 [get_ports {SCLK}]
set_property IOSTANDARD LVCMOS25 [get_ports {SCLK}]
set_property PACKAGE_PIN AD21 [get_ports {CSB}]
set_property IOSTANDARD LVCMOS25 [get_ports {CSB}]
set_property PACKAGE_PIN AB21 [get_ports {MOSI}]
set_property IOSTANDARD LVCMOS25 [get_ports {MOSI}]
set_property PACKAGE_PIN AC21 [get_ports {MISO}]
set_property IOSTANDARD LVCMOS25 [get_ports {MISO}]
set_property PACKAGE_PIN B17 [get_ports {MMC_INT}]
set_property IOSTANDARD LVCMOS25 [get_ports {MMC_INT}]
# ----------------------------------------------------------------------
# ------------------------------ I2C Bus -------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN A17 [get_ports {TWI_SDA}]
set_property IOSTANDARD LVCMOS25 [get_ports {TWI_SDA}]
set_property PACKAGE_PIN B16 [get_ports {TWI_SCL}]
set_property IOSTANDARD LVCMOS25 [get_ports {TWI_SCL}]
set_property PACKAGE_PIN A18 [get_ports {TWI_INT}]
set_property IOSTANDARD LVCMOS25 [get_ports {TWI_INT}]
set_property PACKAGE_PIN B19 [get_ports {TWI_RST}]
set_property IOSTANDARD LVCMOS25 [get_ports {TWI_RST}]
# ----------------------------------------------------------------------
# ------------------------------- Bunny --------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN V11 [get_ports {WR_DAC_SCLK}]
set_property IOSTANDARD LVCMOS15 [get_ports {WR_DAC_SCLK}]
set_property PACKAGE_PIN Y10 [get_ports {WR_DAC_DIN}]
set_property IOSTANDARD LVCMOS15 [get_ports {WR_DAC_DIN}]
set_property PACKAGE_PIN W10 [get_ports {WR_DAC1_SYNC}]
set_property IOSTANDARD LVCMOS15 [get_ports {WR_DAC1_SYNC}]
set_property PACKAGE_PIN Y11 [get_ports {WR_DAC2_SYNC}]
set_property IOSTANDARD LVCMOS15 [get_ports {WR_DAC2_SYNC}]
# ----------------------------------------------------------------------
# ------------------------------- Sysclk -------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN W11 [get_ports {SYSCLK_P}]
set_property IOSTANDARD LVCMOS15 [get_ports {SYSCLK_P}]
set_property PACKAGE_PIN V9 [get_ports {VCXO_EN}]
set_property IOSTANDARD LVCMOS15 [get_ports {VCXO_EN}]
# ----------------------------------------------------------------------
# -------------------------------- UART --------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN C16 [get_ports {Uart_TxD}]
set_property IOSTANDARD LVCMOS25 [get_ports {Uart_TxD}]
set_property PACKAGE_PIN K15 [get_ports {Uart_RxD}]
set_property IOSTANDARD LVCMOS25 [get_ports {Uart_RxD}]
# ----------------------------------------------------------------------
# ------------------------------ pmod J12 ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN C24 [get_ports {Pmod1[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Pmod1[0]}]
set_property PACKAGE_PIN C22 [get_ports {Pmod1[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Pmod1[1]}]
set_property PACKAGE_PIN L23 [get_ports {Pmod1[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Pmod1[2]}]
set_property PACKAGE_PIN D21 [get_ports {Pmod1[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Pmod1[3]}]
set_property PACKAGE_PIN K21 [get_ports {Pmod1[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Pmod1[4]}]
set_property PACKAGE_PIN C18 [get_ports {Pmod1[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Pmod1[5]}]
set_property PACKAGE_PIN C19 [get_ports {Pmod1[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Pmod1[6]}]
set_property PACKAGE_PIN C17 [get_ports {Pmod1[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Pmod1[7]}]
# ----------------------------------------------------------------------
# ------------------------------ pmod J13 ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN AE7 [get_ports {Pmod2[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {Pmod2[0]}]
set_property PACKAGE_PIN V7 [get_ports {Pmod2[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {Pmod2[1]}]
set_property PACKAGE_PIN Y7 [get_ports {Pmod2[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {Pmod2[2]}]
set_property PACKAGE_PIN AF7 [get_ports {Pmod2[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {Pmod2[3]}]
set_property PACKAGE_PIN V8 [get_ports {Pmod2[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {Pmod2[4]}]
set_property PACKAGE_PIN AA8 [get_ports {Pmod2[5]}]
set_property IOSTANDARD LVCMOS15 [get_ports {Pmod2[5]}]
set_property PACKAGE_PIN Y8 [get_ports {Pmod2[6]}]
set_property IOSTANDARD LVCMOS15 [get_ports {Pmod2[6]}]
set_property PACKAGE_PIN W9 [get_ports {Pmod2[7]}]
set_property IOSTANDARD LVCMOS15 [get_ports {Pmod2[7]}]
# ----------------------------------------------------------------------
# -------------------------------- Misc --------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN B9 [get_ports {PHY_RSTN}]
set_property IOSTANDARD LVCMOS25 [get_ports {PHY_RSTN}]
set_property PACKAGE_PIN Y13 [get_ports {LD16}]
set_property IOSTANDARD LVCMOS15 [get_ports {LD16}]
set_property PACKAGE_PIN V12 [get_ports {LD17}]
set_property IOSTANDARD LVCMOS15 [get_ports {LD17}]
# ----------------------------------------------------------------------
# ------------------------------ GTRefclk ------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN D6 [get_ports {GTREFCLK_P[0]}]
set_property PACKAGE_PIN D5 [get_ports {GTREFCLK_N[0]}]
set_property PACKAGE_PIN H6 [get_ports {GTREFCLK_P[1]}]
set_property PACKAGE_PIN H5 [get_ports {GTREFCLK_N[1]}]
set_property PACKAGE_PIN K6 [get_ports {GTREFCLK_P[2]}]
set_property PACKAGE_PIN K5 [get_ports {GTREFCLK_N[2]}]
# ----------------------------------------------------------------------
# ------------------------------- QSFP1 --------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN E3 [get_ports {QSFP1_RX_N[1]}]
set_property PACKAGE_PIN E4 [get_ports {QSFP1_RX_P[1]}]
set_property PACKAGE_PIN D1 [get_ports {QSFP1_TX_N[1]}]
set_property PACKAGE_PIN D2 [get_ports {QSFP1_TX_P[1]}]
set_property PACKAGE_PIN C3 [get_ports {QSFP1_RX_N[2]}]
set_property PACKAGE_PIN C4 [get_ports {QSFP1_RX_P[2]}]
set_property PACKAGE_PIN B1 [get_ports {QSFP1_TX_N[2]}]
set_property PACKAGE_PIN B2 [get_ports {QSFP1_TX_P[2]}]
set_property PACKAGE_PIN B5 [get_ports {QSFP1_RX_N[3]}]
set_property PACKAGE_PIN B6 [get_ports {QSFP1_RX_P[3]}]
set_property PACKAGE_PIN A3 [get_ports {QSFP1_TX_N[3]}]
set_property PACKAGE_PIN A4 [get_ports {QSFP1_TX_P[3]}]
set_property PACKAGE_PIN G3 [get_ports {QSFP1_RX_N[0]}]
set_property PACKAGE_PIN G4 [get_ports {QSFP1_RX_P[0]}]
set_property PACKAGE_PIN F1 [get_ports {QSFP1_TX_N[0]}]
set_property PACKAGE_PIN F2 [get_ports {QSFP1_TX_P[0]}]
# ----------------------------------------------------------------------
# ------------------------------- QSFP2 --------------------------------
# ----------------------------------------------------------------------
set_property PACKAGE_PIN J3 [get_ports {QSFP2_RX_N[1]}]
set_property PACKAGE_PIN J4 [get_ports {QSFP2_RX_P[1]}]
set_property PACKAGE_PIN H1 [get_ports {QSFP2_TX_N[1]}]
set_property PACKAGE_PIN H2 [get_ports {QSFP2_TX_P[1]}]
set_property PACKAGE_PIN N3 [get_ports {QSFP2_RX_N[2]}]
set_property PACKAGE_PIN N4 [get_ports {QSFP2_RX_P[2]}]
set_property PACKAGE_PIN M1 [get_ports {QSFP2_TX_N[2]}]
set_property PACKAGE_PIN M2 [get_ports {QSFP2_TX_P[2]}]
set_property PACKAGE_PIN R3 [get_ports {QSFP2_RX_N[3]}]
set_property PACKAGE_PIN R4 [get_ports {QSFP2_RX_P[3]}]
set_property PACKAGE_PIN P1 [get_ports {QSFP2_TX_N[3]}]
set_property PACKAGE_PIN P2 [get_ports {QSFP2_TX_P[3]}]
set_property PACKAGE_PIN L3 [get_ports {QSFP2_RX_N[0]}]
set_property PACKAGE_PIN L4 [get_ports {QSFP2_RX_P[0]}]
set_property PACKAGE_PIN K1 [get_ports {QSFP2_TX_N[0]}]
set_property PACKAGE_PIN K2 [get_ports {QSFP2_TX_P[0]}]
# ----------------------------------------------------------------------
# ------------------------------- Extras -------------------------------
# ----------------------------------------------------------------------
########
# Clocks
# Clock constraint maps to clock supplied by Spartan (Was in QF2-Pre. TO-DO: Maybe find an equivalent for Marble?)
# create_clock -period 20.000 -name S6_TO_K7_CLK_1 -waveform {0.000 10.000} [get_ports {sys_clk_p}]

# 1300/7 = 185.7143 MHz (Marble)
create_clock -period 5.385 -name "SI57X_A" [get_ports {GTREFCLK_P[1]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets digitizer_U1/clk_ibufgds]

create_clock -period 8.8000 -name U1_clkout3     -waveform {0.000 5.000}  [get_ports {bus_digitizer_U1[4]}]
create_clock -period 2.200  -name U2_DCO         -waveform {1.000 2.250}  [get_ports {bus_digitizer_U2[15]}]
create_clock -period 2.200  -name U3_DCO         -waveform {1.000 2.250}  [get_ports {bus_digitizer_U3[24]}]
create_clock -period 4.400  -name U4_DCO         -waveform {1.000 3.500}  [get_ports {bus_digitizer_U4[13]}]
create_generated_clock -name U4_DCI    -source [get_pins {digitizer_U4/oddr_dci/C}] -divide_by 1 -invert [get_ports {bus_digitizer_U4[29]}]

# Marble
create_clock -period 8.000  -name GTXREFCLK3     -waveform {0.000 4.000}  [get_ports {GTREFCLK_P[2]}]

# This produces warnings. See below.
# create_clock -period 8.000 -name "GMII_TX_CLK" -waveform {0.000 4.000} [get_nets {comms/gmii_tx_clk}]
# create_clock -period 8.000 -name "GMII_RX_CLK" -waveform {0.000 4.000} [get_nets {comms/gmii_rx_clk}]
# create_clock -period 16.000 -name "U32_TX_62_5_CLK" -waveform {0.000 8.000} [get_nets {comms/U32_gt2_tx_usr_clk}]
# create_clock -period 16.000 -name "U32_RX_62_5_CLK" -waveform {0.000 8.000} [get_nets {comms/U32_gt2_rx_usr_clk}]

# It seems that the correct clock definition should point to the output pin of the BUFG/BUFH driving the clock
# Have not tested it, but the MMCM output pin driving the BUFG/BUFH input should work as well
# Since these are being generated by an MMCM, it is advisable by Xilinx UG835 to define them as generated clocks
# Generated clock periods are defined by the -divide/multiply_by argument (see create_generated_clock in UG835)
create_generated_clock -multiply_by 2 -source [get_pins {comms/i_mgt_eth_clks_tx/i_mgt_eth_mmcm/clk_in}] \
-name "GMII_TX_CLK" [get_pins {comms/i_mgt_eth_clks_tx/i_gmii_clk_buf/O}]
create_generated_clock -multiply_by 2 -source [get_pins {comms/i_mgt_eth_clks_rx/i_mgt_eth_mmcm/clk_in}] \
-name "GMII_RX_CLK" [get_pins {comms/i_mgt_eth_clks_rx/i_gmii_clk_buf/O}]
create_generated_clock -divide_by 1 -source [get_pins {comms/i_mgt_eth_clks_tx/i_mgt_eth_mmcm/clk_in}] \
-name "U32_TX_62_5_CLK" [get_pins {comms/i_mgt_eth_clks_tx/i_mgt_usr_clk_buf/O}]
create_generated_clock -divide_by 1 -source [get_pins {comms/i_mgt_eth_clks_rx/i_mgt_eth_mmcm/clk_in}] \
-name "U32_RX_62_5_CLK" [get_pins {comms/i_mgt_eth_clks_rx/i_mgt_usr_clk_buf/O}]

# Clocks
# TO-DO: Review these
create_clock -name sys_clk -period 50.00 [get_ports SYSCLK_P]
create_clock -period 8.00 -name tx_clk [get_ports GTREFCLK_P[0]]
create_clock -period 8.00 -name rx_clk [get_ports RGMII_RX_CLK]

# TODO: Review these
set_false_path -from [get_clocks -of_objects [get_pins comms/clocks_i/MMCME2_BASE_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins comms/clocks_i/MMCME2_BASE_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins comms/clocks_i/MMCME2_BASE_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins comms/clocks_i/MMCME2_BASE_inst/CLKOUT1]]

# Marble
set_clock_groups -name prc -asynchronous \
-group [get_clocks -include_generated_clocks {U1_clkout3}] \
-group [get_clocks -include_generated_clocks {U2_DCO}] \
-group [get_clocks -include_generated_clocks {U3_DCO}] \
-group [get_clocks -include_generated_clocks {U4_DCO U4_DCI}] \
-group [get_clocks -include_generated_clocks GTXREFCLK3] \
-group [get_clocks -include_generated_clocks SI57X_A] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U50_gt_wrap/i_gt0/gt0_txoutclk_out}]] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U50_gt_wrap/i_gt0/gt0_rxoutclk_out}]] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U50_gt_wrap/i_gt1/gt0_txoutclk_out}]] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U50_gt_wrap/i_gt1/gt0_rxoutclk_out}]] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U50_gt_wrap/i_gt2/gt0_txoutclk_out}]] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U50_gt_wrap/i_gt2/gt0_rxoutclk_out}]] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U32_gt_wrap/i_gt0/gt0_txoutclk_out}]] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U32_gt_wrap/i_gt0/gt0_rxoutclk_out}]] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U32_gt_wrap/i_gt1/gt0_txoutclk_out}]] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U32_gt_wrap/i_gt2/gt0_txoutclk_out}]] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U32_gt_wrap/i_gt2/gt0_rxoutclk_out}]] \
-group [get_clocks -include_generated_clocks -of [get_pins {comms/i_U32_gt_wrap/i_gt3/gt0_txoutclk_out}]] \
-group [get_clocks -include_generated_clocks {GMII_TX_CLK}] \
-group [get_clocks -include_generated_clocks {GMII_RX_CLK}] \
-group [get_clocks -include_generated_clocks {U32_TX_62_5_CLK}] \
-group [get_clocks -include_generated_clocks {U32_RX_62_5_CLK}] \
-group [get_clocks -include_generated_clocks sys_clk] \
-group [get_clocks -include_generated_clocks tx_clk] \
-group [get_clocks -include_generated_clocks rx_clk]

########
# Misc
# TO-DO: Review these
# Special pin properties for RGMII
# Invalid to flag RGMII_RX_CLK as IOB TRUE
set_property IOB TRUE [get_ports {RGMII_RX_CTRL}]
set_property IOB TRUE [get_ports {RGMII_RXD*}]
set_property IOB TRUE [get_ports {RGMII_TX*}]
set_property SLEW FAST [get_ports {RGMII_TX*}]

# Bank 0 setup
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 2.5 [current_design]
